### ISSUE TITLE
Consider updating to freedesktop 18.08 and openjdk 11

### ISSUE THREAD

**Issue by mbooth101** [flathub/com.bladecoder.adventure-editor#1]
I believe by moving to openjdk 11 you will no longer need the custom cacerts file.

**Comment by danigm** [comment]
I'm trying to update to openjdk11, but I'm having some issues when running gradle, I need to find what's the problem:

```
could not determine java version from '11.0.1'.
```

https://github.com/flathub/com.bladecoder.adventure-editor/pull/2

**Comment by danigm** [comment]
I'll link here the PR in the original project: https://github.com/bladecoder/bladecoder-adventure-engine/pull/40
